name: CMake on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env: 
    VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - uses: actions/checkout@v4
    
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Configure CMake
      run: cmake --preset ninja-multi-vcpkg

    - name: Build
      run: cmake --build --preset ninja-vcpkg-release


